### ISSUE TITLE
There was an error in magic function detect_rdata_single

### ISSUE THREAD

**Issue by jtrakk** [JuliaIO/FileIO.jl#341] opened 2021-06-11 05:36 UTC
This is running under `@distributed` on a single machine. It's telling me to open an issue so I am.

```jl
┌ Error: There was an error in magic function detect_rdata_single.
│ Please open an issue at FileIO.jl.
│   exception =
│    EOFError: read end of file
│    Stacktrace:
│      [1] read(s::IOStream, #unused#::Type{UInt8})
│        @ Base ./iostream.jl:399
│      [2] detect_rdata_single(io::IOStream)
│        @ FileIO ~/.julia/packages/FileIO/40aie/src/registry.jl:75
│      [3] match(io::IOStream, magic::Function)
│        @ FileIO ~/.julia/packages/FileIO/40aie/src/query.jl:143
│      [4] querysym_all(io::IOStream)
│        @ FileIO ~/.julia/packages/FileIO/40aie/src/query.jl:169
│      [5] (::FileIO.var"#5#9"{Symbol})(io::IOStream)
│        @ FileIO ~/.julia/packages/FileIO/40aie/src/query.jl:96
│      [6] open(f::FileIO.var"#5#9"{Symbol}, args::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ Base ./io.jl:330
│      [7] open
│        @ ./io.jl:328 [inlined]
│      [8] querysym(filename::String; checkfile::Bool)
│        @ FileIO ~/.julia/packages/FileIO/40aie/src/query.jl:93
│      [9] query(filename::String; checkfile::Bool)
│        @ FileIO ~/.julia/packages/FileIO/40aie/src/query.jl:76
│     [10] query
│        @ ~/.julia/packages/FileIO/40aie/src/query.jl:75 [inlined]
│     [11] save(filename::String, fig::Figure; args::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ Makie ~/.julia/packages/Makie/Yd637/src/display.jl:221
│     [12] save(filename::String, fig::Figure)
│        @ Makie ~/.julia/packages/Makie/Yd637/src/display.jl:221
```

**Comment by johnnychen94** [comment] 2021-06-11 05:50
Could you provide a minimal working example for this?

**Comment by jtrakk** [comment] 2021-06-11 06:18
I don't think I can, sorry. Feel free to close if you like.

**Comment by johnnychen94** [comment] 2021-06-11 06:27
Duplicate of #338, but if there's no MWE provided it would be very hard to figure out what's wrong here.

**Comment by ederag** [comment] 2021-06-18 16:49
It should be reproducible with the #338 mwe together with an empty `test1.pdf` already present, e.g. by
```
rm test1.pdf
touch test1.pdf
```

**Comment by johnnychen94** [comment] 2021-06-19 17:27
close in favor of #338

**Closed by johnnychen94** 2021-06-19 17:27 UTC
